hooks:
  - name: "Clippy Checks"
    entry: "cargo clippy --lib -- -D warnings"
    language: "system"
    pass_filenames: false
    stages: ["commit"]
    description: "Run clippy linter to check for common Rust mistakes"
