[32m[1m       Using[0m[39m [37m[1mCliArgument("pg18")[0m[39m and `pg_config` from [36m/usr/bin/pg_config[39m
[32m[1m    Building[0m[39m for SQL generation with features `pg18`
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
[32m[1m  Discovered[0m[39m [36m[1m31[0m[39m SQL entities: [36m[1m0[0m[39m schemas ([36m[1m0[0m[39m unique), [36m[1m24[0m[39m functions, [36m[1m1[0m[39m types, [36m[1m0[0m[39m enums, [36m[1m4[0m[39m sqls, [36m[1m0[0m[39m ords, [36m[1m0[0m[39m hashes, [36m[1m0[0m[39m aggregates, [36m[1m2[0m[39m triggers
[32m[1m  Rebuilding[0m[39m [36mpgrx_embed[39m, in debug mode, for SQL generation with features [36mpg18[39m
   Compiling pg_tviews v0.1.0-beta.1 (/home/lionel/code/pg_tviews)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.17s
[32m[1m     Writing[0m[39m SQL entities to /dev/stdout
/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:94

CREATE TABLE IF NOT EXISTS public.pg_tview_audit_log (
    log_id BIGSERIAL PRIMARY KEY,
    operation TEXT NOT NULL,  -- CREATE, DROP, ALTER, REFRESH
    entity TEXT NOT NULL,
    performed_by TEXT NOT NULL DEFAULT current_user,
    performed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    details JSONB,
    client_addr INET DEFAULT inet_client_addr(),
    client_port INTEGER DEFAULT inet_client_port()
);

CREATE INDEX IF NOT EXISTS idx_audit_log_entity ON pg_tview_audit_log(entity);
CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON pg_tview_audit_log(performed_at DESC);

COMMENT ON TABLE pg_tview_audit_log IS 'Audit log for TVIEW operations';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:67

-- Event trigger for CREATE TABLE interception
-- Fires AFTER the table is created, providing safe SPI context
-- The handler function pg_tviews_handle_ddl_event() is implemented in Rust (src/event_trigger.rs)

-- Create the event trigger
DROP EVENT TRIGGER IF EXISTS pg_tviews_ddl_end;
CREATE EVENT TRIGGER pg_tviews_ddl_end
    ON ddl_command_end
    WHEN TAG IN ('CREATE TABLE', 'SELECT INTO')
    EXECUTE FUNCTION pg_tviews_handle_ddl_event();

-- Add comment
COMMENT ON EVENT TRIGGER pg_tviews_ddl_end IS
'Intercepts CREATE TABLE tv_* commands and converts them to TVIEWs';

-- Note: Both pg_tviews_handle_ddl_event() and pg_tviews_convert_table()
-- are auto-generated by pgrx from src/event_trigger.rs
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:34

    CREATE TABLE IF NOT EXISTS public.pg_tview_meta (
        entity TEXT NOT NULL PRIMARY KEY,
        view_oid OID NOT NULL,
        table_oid OID NOT NULL,
        definition TEXT NOT NULL,
        dependencies OID[] NOT NULL DEFAULT '{}',
        fk_columns TEXT[] NOT NULL DEFAULT '{}',
        uuid_fk_columns TEXT[] NOT NULL DEFAULT '{}',
        dependency_types TEXT[] NOT NULL DEFAULT '{}',
        dependency_paths TEXT[][] NOT NULL DEFAULT '{}',
        array_match_keys TEXT[] NOT NULL DEFAULT '{}',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS public.pg_tview_helpers (
        helper_name TEXT NOT NULL PRIMARY KEY,
        is_helper BOOLEAN NOT NULL DEFAULT TRUE,
        used_by TEXT[] NOT NULL DEFAULT '{}',
        depends_on TEXT[] NOT NULL DEFAULT '{}',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    COMMENT ON TABLE public.pg_tview_meta IS 'Metadata for TVIEW materialized tables';
    COMMENT ON TABLE public.pg_tview_helpers IS 'Tracks helper views used by TVIEWs';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:116

-- Queue monitoring view
CREATE OR REPLACE VIEW pg_tviews_queue_realtime AS
SELECT
    current_setting('application_name') as session,
    pg_backend_pid() as backend_pid,
    txid_current() as transaction_id,
    0 as queue_size,  -- TODO: Implement queue introspection
    ARRAY[]::TEXT[] as entities,
    NOW() as last_enqueued;

-- Cache statistics view
CREATE OR REPLACE VIEW pg_tviews_cache_stats AS
SELECT
    'graph_cache' as cache_type,
    0::BIGINT as entries,
    '0 bytes' as estimated_size
UNION ALL
SELECT
    'table_cache' as cache_type,
    0::BIGINT as entries,
    '0 bytes' as estimated_size;

-- Performance summary view
CREATE OR REPLACE VIEW pg_tviews_performance_summary AS
SELECT
    entity,
    COUNT(*) as total_refreshes,
    0.0 as avg_refresh_ms,
    NOW() as last_refresh
FROM pg_tview_meta
GROUP BY entity;
/* </end connected objects> */

/* <begin connected objects> */
-- src/schema/mod.rs:38
-- pg_tviews::schema::TViewSchema
CREATE TYPE TViewSchema;

-- src/schema/mod.rs:38
-- pg_tviews::schema::tviewschema_in
CREATE  FUNCTION "tviewschema_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS TViewSchema /* core::option::Option<pg_tviews::schema::TViewSchema> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tviewschema_in_wrapper';

-- src/schema/mod.rs:38
-- pg_tviews::schema::tviewschema_out
CREATE  FUNCTION "tviewschema_out"(
	"input" TViewSchema /* pg_tviews::schema::TViewSchema */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tviewschema_out_wrapper';

-- src/schema/mod.rs:38
-- pg_tviews::schema::TViewSchema
CREATE TYPE TViewSchema (
	INTERNALLENGTH = variable,
	INPUT = tviewschema_in, /* pg_tviews::schema::tviewschema_in */
	OUTPUT = tviewschema_out, /* pg_tviews::schema::tviewschema_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:307
-- pg_tviews::pg_tviews_analyze_select
CREATE  FUNCTION "pg_tviews_analyze_select"(
	"sql" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_analyze_select_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:597
-- pg_tviews::pg_tviews_cascade
CREATE  FUNCTION "pg_tviews_cascade"(
	"base_table_oid" oid, /* pgrx_pg_sys::submodules::oids::Oid */
	"pk_value" bigint /* i64 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_cascade_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:129
-- pg_tviews::pg_tviews_check_jsonb_ivm
CREATE  FUNCTION "pg_tviews_check_jsonb_ivm"() RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_check_jsonb_ivm_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:350
-- pg_tviews::pg_tviews_commit_prepared
CREATE  FUNCTION "pg_tviews_commit_prepared"(
	"gid" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), pg_tviews::error::TViewError> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_commit_prepared_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/ddl/mod.rs:63
-- pg_tviews::ddl::pg_tviews_convert_existing_table
CREATE  FUNCTION "pg_tviews_convert_existing_table"(
	"table_name" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::string::String> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_convert_existing_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/event_trigger.rs:100
-- pg_tviews::event_trigger::pg_tviews_convert_table
CREATE  FUNCTION "pg_tviews_convert_table"(
	"table_name" TEXT /* alloc::string::String */
) RETURNS VOID /* core::result::Result<(), alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_convert_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/ddl/mod.rs:30
-- pg_tviews::ddl::pg_tviews_create
CREATE  FUNCTION "pg_tviews_create"(
	"tview_name" TEXT, /* &str */
	"select_sql" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::string::String> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_create_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:159
-- pg_tviews::pg_tviews_debug_queue
CREATE  FUNCTION "pg_tviews_debug_queue"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_debug_queue_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:665
-- pg_tviews::pg_tviews_delete
CREATE  FUNCTION "pg_tviews_delete"(
	"base_table_oid" oid, /* pgrx_pg_sys::submodules::oids::Oid */
	"pk_value" bigint /* i64 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_delete_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/ddl/mod.rs:46
-- pg_tviews::ddl::pg_tviews_drop
CREATE  FUNCTION "pg_tviews_drop"(
	"tview_name" TEXT, /* &str */
	"if_exists" bool DEFAULT false /* bool */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::string::String> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_drop_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/event_trigger.rs:23
-- pg_tviews::event_trigger::pg_tviews_handle_ddl_event
CREATE  FUNCTION "pg_tviews_handle_ddl_event"() RETURNS VOID /* core::result::Result<(), alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_handle_ddl_event_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:203
-- pg_tviews::pg_tviews_health_check
CREATE  FUNCTION "pg_tviews_health_check"() RETURNS TABLE (
	"status" TEXT,  /* alloc::string::String */
	"component" TEXT,  /* alloc::string::String */
	"message" TEXT,  /* alloc::string::String */
	"severity" TEXT  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_health_check_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:85
-- pg_tviews::pg_tviews_hook_status
CREATE  FUNCTION "pg_tviews_hook_status"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_hook_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:325
-- pg_tviews::pg_tviews_infer_types
CREATE  FUNCTION "pg_tviews_infer_types"(
	"table_name" TEXT, /* &str */
	"columns" TEXT[] /* alloc::vec::Vec<alloc::string::String> */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_infer_types_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:649
-- pg_tviews::pg_tviews_insert
CREATE  FUNCTION "pg_tviews_insert"(
	"base_table_oid" oid, /* pgrx_pg_sys::submodules::oids::Oid */
	"pk_value" bigint /* i64 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_insert_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:935
-- pg_tviews::pg_tviews_performance_stats
CREATE  FUNCTION "pg_tviews_performance_stats"() RETURNS TABLE (
	"entity" TEXT,  /* alloc::string::String */
	"table_size" TEXT,  /* alloc::string::String */
	"total_size" TEXT,  /* alloc::string::String */
	"row_count" bigint,  /* i64 */
	"index_count" INT  /* i32 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_performance_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:136
-- pg_tviews::pg_tviews_queue_stats
CREATE  FUNCTION "pg_tviews_queue_stats"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_queue_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:492
-- pg_tviews::pg_tviews_recover_prepared_transactions
CREATE  FUNCTION "pg_tviews_recover_prepared_transactions"() RETURNS TABLE (
	"gid" TEXT,  /* alloc::string::String */
	"queue_size" INT,  /* i32 */
	"status" TEXT  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_recover_prepared_transactions_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/ddl/mod.rs:77
-- pg_tviews::ddl::pg_tviews_refresh
CREATE  FUNCTION "pg_tviews_refresh"(
	"tview_name" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::string::String> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_refresh_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:410
-- pg_tviews::pg_tviews_rollback_prepared
CREATE  FUNCTION "pg_tviews_rollback_prepared"(
	"gid" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), pg_tviews::error::TViewError> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_rollback_prepared_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:874
-- pg_tviews::pg_tviews_show_cascade_path
CREATE  FUNCTION "pg_tviews_show_cascade_path"(
	"entity" TEXT /* &str */
) RETURNS TABLE (
	"depth" INT,  /* i32 */
	"entity_name" TEXT,  /* alloc::string::String */
	"depends_on" TEXT  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_show_cascade_path_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:79
-- pg_tviews::pg_tviews_version
CREATE  FUNCTION "pg_tviews_version"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pg_tviews_version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/trigger.rs:81
-- pg_tviews::trigger::pg_tview_stmt_trigger_handler
CREATE FUNCTION "pg_tview_stmt_trigger_handler"()
	RETURNS TRIGGER
	LANGUAGE c
	AS 'MODULE_PATHNAME', 'pg_tview_stmt_trigger_handler_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/trigger.rs:31
-- pg_tviews::trigger::pg_tview_trigger_handler
CREATE FUNCTION "pg_tview_trigger_handler"()
	RETURNS TRIGGER
	LANGUAGE c
	AS 'MODULE_PATHNAME', 'pg_tview_trigger_handler_wrapper';
/* </end connected objects> */

