-- pg_tviews 0.1.0-beta.20 → 0.1.0-beta.21
--
-- Pending upgrade script: a pull request that changes the extension SQL adds its
-- statements here (docs/development/extension-versioning.md). Released scripts are
-- never edited.
